name: Pull Request Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Check types
      run: npx tsc --noEmit
    
    - name: Check code formatting
      run: npx prettier --check .
    
    - name: Run ESLint
      run: npm run lint
    
    - name: Check for duplicate dependencies
      run: npx depcheck
    
    - name: Check bundle size
      run: npx next build && npx next bundle-analyzer
    
    - name: Run security audit
      run: npm audit
      continue-on-error: true

  preview:
    needs: validate
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    # Add your preview deployment steps here
    # Example for Vercel preview:
    - name: Deploy Preview to Vercel
      run: |
        npm install --global vercel
        vercel deploy --token ${{ secrets.VERCEL_TOKEN }}
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}