name: Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      
      - name: Scan with npm audit
        run: npm audit --audit-level=high
      
      - name: Lighthouse Performance Check
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://your-staging-url.com
          budgetPath: ./budget.json
          uploadArtifacts: true